// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XPRESS_V1_Backend.Data;

#nullable disable

namespace XPRESS_V1_Backend.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20250523070919_xpressv1_testing")]
    partial class xpressv1_testing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XPRESS_V1.Models.Riona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Riona");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.Advait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Advait");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NewStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("OldStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LogId");

                    b.HasIndex("NewStatusId");

                    b.HasIndex("OldStatusId");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.Mahesh", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Maheshs");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.Project", b =>
                {
                    b.Property<string>("ProjectCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectManager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectCode");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.RequestApproval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApprovalId"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApprovalLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ApproverId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NewStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.HasKey("ApprovalId");

                    b.HasIndex("ApproverId");

                    b.HasIndex("NewStatusId");

                    b.HasIndex("PreviousStatusId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestApprovals");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.RequestStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusId");

                    b.ToTable("RequestStatuses");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.TestTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TestTables");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.Test_Tables_George", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TestTables_George");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.TicketOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OptionId"));

                    b.Property<string>("AdditionalDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AirlineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BookingClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.HasKey("OptionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RequestId");

                    b.ToTable("TicketOptions");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.TravelMode", b =>
                {
                    b.Property<int>("TravelModeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TravelModeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TravelModeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TravelModeId");

                    b.ToTable("TravelModes");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.TravelRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<bool?>("AttendedCct")
                        .HasColumnType("boolean");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationPlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DropoffLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("FoodPreference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAccommodationRequired")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsDropoffRequired")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPickupRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurposeOfTravel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SelectedTicketOptionId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourcePlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalExpense")
                        .HasColumnType("numeric");

                    b.Property<string>("TravelAgencyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TravelModeId")
                        .HasColumnType("integer");

                    b.Property<int>("TravelTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("TripTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedTicketPdfPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RequestId");

                    b.HasIndex("CurrentStatusId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectCode");

                    b.HasIndex("SelectedTicketOptionId");

                    b.HasIndex("TravelModeId");

                    b.HasIndex("TravelTypeId");

                    b.HasIndex("TripTypeId");

                    b.ToTable("TravelRequests");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.TravelType", b =>
                {
                    b.Property<int>("TravelTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TravelTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TravelTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TravelTypeId");

                    b.ToTable("TravelTypes");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.TripType", b =>
                {
                    b.Property<int>("TripTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TripTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TripTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TripTypeId");

                    b.ToTable("TripTypes");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.User", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DuHeadId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReportingManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DuHeadId");

                    b.HasIndex("ReportingManagerId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.AuditLog", b =>
                {
                    b.HasOne("XPRESS_V1_Backend.Models.RequestStatus", "NewStatus")
                        .WithMany("AuditLogsAsNewStatus")
                        .HasForeignKey("NewStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("XPRESS_V1_Backend.Models.RequestStatus", "OldStatus")
                        .WithMany("OldStatuses")
                        .HasForeignKey("OldStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("XPRESS_V1_Backend.Models.TravelRequest", "TravelRequest")
                        .WithMany("AuditLogs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XPRESS_V1_Backend.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewStatus");

                    b.Navigation("OldStatus");

                    b.Navigation("TravelRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.RequestApproval", b =>
                {
                    b.HasOne("XPRESS_V1_Backend.Models.User", "Approver")
                        .WithMany("Approvals")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XPRESS_V1_Backend.Models.RequestStatus", "NewStatus")
                        .WithMany("RequestApprovalsAsNewStatus")
                        .HasForeignKey("NewStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XPRESS_V1_Backend.Models.RequestStatus", "PreviousStatus")
                        .WithMany("PreviousStatuses")
                        .HasForeignKey("PreviousStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("XPRESS_V1_Backend.Models.TravelRequest", "TravelRequest")
                        .WithMany("RequestApprovals")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("NewStatus");

                    b.Navigation("PreviousStatus");

                    b.Navigation("TravelRequest");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.TicketOption", b =>
                {
                    b.HasOne("XPRESS_V1_Backend.Models.User", "Creator")
                        .WithMany("CreatedTicketOptions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XPRESS_V1_Backend.Models.TravelRequest", "TravelRequest")
                        .WithMany("TicketOptions")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("TravelRequest");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.TravelRequest", b =>
                {
                    b.HasOne("XPRESS_V1_Backend.Models.RequestStatus", "CurrentStatus")
                        .WithMany("TravelRequests")
                        .HasForeignKey("CurrentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XPRESS_V1_Backend.Models.User", "Employee")
                        .WithMany("TravelRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XPRESS_V1_Backend.Models.Project", "Project")
                        .WithMany("TravelRequests")
                        .HasForeignKey("ProjectCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XPRESS_V1_Backend.Models.TicketOption", "SelectedTicketOption")
                        .WithMany("SelectedByTravelRequests")
                        .HasForeignKey("SelectedTicketOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("XPRESS_V1_Backend.Models.TravelMode", "TravelMode")
                        .WithMany("TravelRequests")
                        .HasForeignKey("TravelModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XPRESS_V1_Backend.Models.TravelType", "TravelType")
                        .WithMany("TravelRequests")
                        .HasForeignKey("TravelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XPRESS_V1_Backend.Models.TripType", "TripType")
                        .WithMany("TravelRequests")
                        .HasForeignKey("TripTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentStatus");

                    b.Navigation("Employee");

                    b.Navigation("Project");

                    b.Navigation("SelectedTicketOption");

                    b.Navigation("TravelMode");

                    b.Navigation("TravelType");

                    b.Navigation("TripType");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.User", b =>
                {
                    b.HasOne("XPRESS_V1_Backend.Models.User", "DuHead")
                        .WithMany("DepartmentMembers")
                        .HasForeignKey("DuHeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("XPRESS_V1_Backend.Models.User", "ReportingManager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ReportingManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DuHead");

                    b.Navigation("ReportingManager");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.Project", b =>
                {
                    b.Navigation("TravelRequests");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.RequestStatus", b =>
                {
                    b.Navigation("AuditLogsAsNewStatus");

                    b.Navigation("OldStatuses");

                    b.Navigation("PreviousStatuses");

                    b.Navigation("RequestApprovalsAsNewStatus");

                    b.Navigation("TravelRequests");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.TicketOption", b =>
                {
                    b.Navigation("SelectedByTravelRequests");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.TravelMode", b =>
                {
                    b.Navigation("TravelRequests");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.TravelRequest", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("RequestApprovals");

                    b.Navigation("TicketOptions");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.TravelType", b =>
                {
                    b.Navigation("TravelRequests");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.TripType", b =>
                {
                    b.Navigation("TravelRequests");
                });

            modelBuilder.Entity("XPRESS_V1_Backend.Models.User", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedTicketOptions");

                    b.Navigation("DepartmentMembers");

                    b.Navigation("Subordinates");

                    b.Navigation("TravelRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
